### PR TITLE
Fixed TravisCI.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Please check and merge if you like.

**Comment by emanuelschuetze** [comment]
Mmh, I don't like it so much to use this (production ready) plugin as example/demo plugin for slides. A simple welcome slide is not really useable for this plugin. And it does not support multiprojector.

Suggestion: Make a real example plugin with dummy slides/views and keep this csv-export-plugin minimal.

**Comment by emanuelschuetze** [comment]
@normanjaeckel ping

**Comment by normanjaeckel** [comment]
Hm. Then please strip out my first commit to update this plugin for upcoming v2.1

**Comment by emanuelschuetze** [comment]
see #34

**Pull request closed without merging**
